name: metsyn-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.0
  - openpyxl
  - great-expectations
  - pandera
  - pydantic>=2.0
  - scikit-learn   # imputación KNN (etapa impute del ETL)
  - fastapi>=0.110
  - uvicorn
  - python-dotenv
  - dvc
  - pytest
  - ruff
  - pip
  - pip:
      - supabase
      - redis
