name: metsyn-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - scikit-learn
  - xgboost
  - pandas>=2.0
  - numpy
  - shap
  - lime
  - matplotlib
  - dvc
  - jupyterlab
  - pip
  - pip:
      - missingpy
